app = "stargate-backend-iozzeqvj"
primary_region = "iad"

[build]

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  interval = "15s"
  grace_period = "5s"
  method = "GET"
  path = "/"
  protocol = "http"
  timeout = "10s"

[processes]
  app = "python -m uvicorn main:app --host 0.0.0.0 --port 8080"

[deploy]
  release_command = "python -m uvicorn main:app --host 0.0.0.0 --port 8080"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
